include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
